cors:
  originPatterns: ${CORS_ORIGINS}
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bopereg?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  pathsToMatch:
    - /auth/**
    - /**/v1/**
  swagger-ui:
    use-root-path: true
