server:
  port: 80
cors:
  originPatterns: ${CORS_ORIGINS}
file:
  upload-dir: ${HOME}/tmpfile
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bopereg?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB # configuration to establish a limit to save in memory, when the size is greater than that the data is saved on disk
      max-file-size: 200MB # configuration to establish the max size of a file
      max-request-size: 215MB
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  pathsToMatch:
    - /auth/**
    - /**/v1/**
  swagger-ui:
    use-root-path: true
