cors:
  originPatterns: ${CORS_ORIGINS}
file:
  upload-dir: ${HOME}/tmpfile
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bopereg?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB # configuração para estabelecemos um limite para salvar em memória, quando passar disso é salvo no disco
      max-file-size: 200MB # configuração para estabelecer o tamanho máximo de um arquivo
      max-request-size: 215MB
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  pathsToMatch:
    - /auth/**
    - /**/v1/**
  swagger-ui:
    use-root-path: true
